// src/example-vue-project/src/components/OrdersList.vue
<script setup lang="ts">
import { ref } from 'vue'

defineProps<{ msg: string }>()

</script>

<template>
  
  <table>
    <thead>
        <tr>
            <th>ID</th>
            <th>Created On</th>
        </tr>
    </thead>
    <tbody>
        <tr></tr>
    </tbody>
  </table>
</template>

<style scoped>
.read-the-docs {
  color: #888;
}
</style>

// src/example-react-project/src/components/OrdersList.tsx

export function OrdersList(){

    return <table>
        <thead>
            <tr>
                <th>ID</th>
                <th>Created On</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <th>1</th>
                <td>{new Date().toString()}</td>
            </tr>
        </tbody>
    </table>

}
